defaults: &defaults
  working_directory: '~/project'

#########################JOBS########################################
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: 'Install yarn'
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "rocket-api/yarn.lock" }}-{{ checksum "mock-api/yarn.lock"}}
            - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "rocket-api/yarn.lock" }}
            - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependencies-{{ .Branch }}
            - dependencies
      - run:
          name: 'Install dependencies'
          command: |
            npm install
            yarn run bootstrap

      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "rocket-api/yarn.lock" }}-{{ checksum "mock-api/yarn.lock"}}
          paths:
            - node_modules
            - rocket-api/node_modules
            - mock-api/node_modules

############################WORKFLOWS###################################
workflows:
  version: 2

  pipeline:
    jobs:
      - build
