defaults: &defaults
  docker:
        - image: node:8.9.4
attach_workspace: &attach_workspace
  attach_workspace:
    at: '.'

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: '.'
    paths: [ '.' ]

#########################JOBS#########################################
version: 2
jobs:
  install_dependencies:
    <<: *defaults
    working_directory: '~/project'
    steps:
      - checkout
      - run:
          name: 'Install yarn'
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "rocket-api/yarn.lock" }}-{{ checksum "mock-api/yarn.lock"}}
            - dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "rocket-api/yarn.lock" }}
            - dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - dependencies-{{ .Branch }}
            - dependencies
      - run:
          name: 'Install dependencies'
          command: |
            yarn add lerna -D
            yarn run bootstrap

      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "rocket-api/yarn.lock" }}-{{ checksum "mock-api/yarn.lock"}}
          paths:
            - node_modules
            - rocket-api/node_modules
            - mock-api/node_modules
      - *persist_workspace

  extra:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: 'dumb'
          command:  |
             ls -la
      - *persist_workspace


  extra_extra:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: '.'
          paths: [ 'package.json' ]

#
  extra_extra_extra:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 'test'
          command: |
            rm -f package.json
      - persist_to_workspace:
          root: '.'
          paths: [ 'package.json' ]


  extra_extra_extra_extra:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: 'ls'
          command: |
            ls -la

  build:
    <<: *defaults
    working_directory: '~/project_tmp'
    steps:
      - checkout
      - run:
          name: 'Install yarn'
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          keys:
            - prod-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "rocket-api/yarn.lock" }}-{{ checksum "mock-api/yarn.lock"}}
            - prod-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "rocket-api/yarn.lock" }}
            - prod-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - prod-dependencies-{{ .Branch }}
            - prod-dependencies
      - run:
          name: 'Remove Dependencies && Zip Artifacts'
          command: |
            yarn add lerna -D
            yarn run clean-dev-dependencies

      - save_cache:
          key: prod-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "rocket-api/yarn.lock" }}-{{ checksum "mock-api/yarn.lock"}}
          paths:
            - node_modules
            - rocket-api/node_modules
            - mock-api/node_modules
      - run:
          name: 'create something'
          command: |
            mkdir /tmp/dir
      - *persist_workspace

  echo:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 'echo helloworld'
          command: |
            mkdir /coverageReport
            cp README.md /coverageReport
      - store_artifacts:
          root: '.'
          path: /coverageReport

  hello:
    working_directory: '~/project_tmp'
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - attach_workspace:
         at: /tmp/dir
#      - run:
#          name: Install Docker client
#          command: |
#              set -x
#              VER="17.03.0-ce"
#              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
#              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#              mv /tmp/docker/* /usr/bin
#      - run:
#          name: Install Docker Compose
#          command: |
#              curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#              chmod +x ~/docker-compose
#              mv ~/docker-compose /usr/bin/docker-compose
      - run:
          name: 'sample'
          command: |
              docker pull hapijs/hapijs.com


############################WORKFLOWS###################################
workflows:
  version: 2

  pipeline:
    jobs:
#     - install_dependencies
#     - build
#      - extra:
#          requires: ['install_dependencies']
#      - extra_extra:
#          requires: ['extra']
#      - hello:
#        requires: ['extra', 'build']
    - extra_extra
    - extra_extra_extra
    - extra_extra_extra_extra:
        requires: ['extra_extra', 'extra_extra_extra']