defaults: &defaults
  working_directory: '~/project'

machine:
  pre:
    - npm install -g lerna
    - mkdir ~/.yarn-cache
  node:
    version: 8.9.4

dependencies:
  pre:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  cache_directories:
    - ~/.yarn-cache
  override:
    - yarn bootstrap

#########################JOBS########################################
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout

############################WORKFLOWS###################################
workflows:
  version: 2

  pipeline:
    jobs:
      #build
      - checkout
